language: node_js
node_js:
- '4'
install:
- npm i
after_success:
- "./tools/gh_pages.sh"
env:
  global:
    secure: ejL+ZrOJ5y6I3eGR638KU7oq4g8SYLBNNdqX35gacu/RQihd58f1Y6lQhZrl6DoAfX4uOMJi/1l/9iL5d4zCgIijcJ3mTwP8cHHYHT800T0ciXyMRhOB6COyk5xSv7IlwWQbiRVDYIDVFlytl4nML+s6bMrPpyk5dPOqqRl3YtycMpTFl8JsB/GQRxcJ7cxP+YRXRe3QCzp6T+p2gt+hOJLAWLyGz13eRd5LEiWuGy8lim11poJGzSV6d32N5YHOVXKYODLf3nDQN8gQVpMi5Kgj0E9fk4Iu6t3c86nOl1WsqCjEPbV8BauEr5OyEAhzi2WSz5C3kk34Xy2I8J92N3zCo4ZyZjiqc19eAC/Jc1P4dYdo2pTaai2xtOf3MzTt2VrvaZlC3rtvjztA7VR7geYyqgWXnXxc2FGEiniI84LXRjKUZFUe9FglmPFhzXzL1y3iodLn3jHHpovmRqE3Omgklf5Hza9QcHYYbH4dBgRML6QnJFsvoayloGpDO2XAX91Rtv6wV/P1cpCZXUramJd6fz7Ky+WjN/Ny6llJeE5LkZjGwORqtnL7kfJoaRw3SpAOVSSdPpkOMihQQfP1opxo3NQ0TlLkbpfIt3zX14VX5bAtNEAVnw43+arR0fmaKtVYlHl0QcplkwlEIeO0a9mwKTL7PSE8xfTbTwqwbxE=
